
package com.webservice.provider;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserAPIImpl", targetNamespace = "http://provider.webservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserAPIImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://provider.webservice.com/", className = "com.webservice.provider.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://provider.webservice.com/", className = "com.webservice.provider.LoginResponse")
    @Action(input = "http://provider.webservice.com/UserAPIImpl/loginRequest", output = "http://provider.webservice.com/UserAPIImpl/loginResponse")
    public String login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
